import sqlite3
from pathlib import Path

DB_PATH = Path("database/tpa_match_demo.db")


def connect_db():
    if not DB_PATH.exists():
        raise FileNotFoundError(
            f"Database not found at {DB_PATH}. Run scripts/create_database.py first."
        )

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def insert_vendor(cursor, vendor):
    cursor.execute(
        """
        INSERT INTO vendors (
            vendor_name,
            vendor_type,
            headquarters_state,
            company_size,
            years_in_business,
            website,
            active_status,
            ideal_client_size,
            program_type_fit,
            pricing_level,
            satisfaction_score,
            avg_response_time_days,
            reporting_score,
            data_quality_score,
            source,
            source_confidence,
            last_updated,
            verified_by_human,
            notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            vendor["vendor_name"],
            vendor.get("vendor_type", "TPA"),
            vendor.get("headquarters_state"),
            vendor.get("company_size"),
            vendor.get("years_in_business"),
            vendor.get("website"),
            vendor.get("active_status", "active"),
            vendor.get("ideal_client_size"),
            vendor.get("program_type_fit"),
            vendor.get("pricing_level"),
            vendor.get("satisfaction_score"),
            vendor.get("avg_response_time_days"),
            vendor.get("reporting_score"),
            vendor.get("data_quality_score"),
            vendor.get("source"),
            vendor.get("source_confidence"),
            vendor.get("last_updated"),
            vendor.get("verified_by_human", 0),
            vendor.get("notes"),
        ),
    )

    return cursor.lastrowid


def insert_many_to_vendor_table(cursor, table_name, vendor_id, values):
    for item in values:
        columns = item.keys()
        placeholders = ", ".join(["?"] * (len(columns) + 1))
        column_sql = ", ".join(["vendor_id", *columns])

        cursor.execute(
            f"""
            INSERT INTO {table_name} ({column_sql})
            VALUES ({placeholders})
            """,
            (vendor_id, *item.values()),
        )


def seed_vendors(cursor):
    vendors = [
        {
            "vendor_name": "NorthStar Claims",
            "headquarters_state": "MN",
            "company_size": "mid_market",
            "years_in_business": 18,
            "website": "https://example.com/northstar",
            "ideal_client_size": "250-2500 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 91,
            "avg_response_time_days": 1.6,
            "reporting_score": 8.5,
            "data_quality_score": 8.0,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-02-01",
            "verified_by_human": 1,
            "notes": "Strong Midwest workers compensation TPA with return-to-work focus.",
            "states": [
                {"state_code": "MN", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "WI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "IL", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "strong"},
                {"industry": "construction", "experience_level": "moderate"},
                {"industry": "healthcare", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": "Dedicated RTW coordination."},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": "In-house clinical resources."},
                {"service_name": "litigation_management", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": "Monthly dashboards available."},
                {"service_name": "origami_integration", "service_level": "moderate", "provided_in_house": 0, "notes": "Prior RMIS export experience."},
            ],
        },
        {
            "vendor_name": "Midwest TPA Group",
            "headquarters_state": "WI",
            "company_size": "mid_market",
            "years_in_business": 24,
            "website": "https://example.com/midwest-tpa",
            "ideal_client_size": "100-1500 employees",
            "program_type_fit": "high_deductible, guaranteed_cost",
            "pricing_level": "medium_low",
            "satisfaction_score": 84,
            "avg_response_time_days": 2.2,
            "reporting_score": 7.0,
            "data_quality_score": 7.5,
            "source": "proposal_summary",
            "source_confidence": "medium",
            "last_updated": "2025-11-18",
            "verified_by_human": 1,
            "notes": "Good regional WC option, but technology details are incomplete.",
            "states": [
                {"state_code": "MN", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "WI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "strong", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "auto_liability", "capability_level": "limited", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "moderate"},
                {"industry": "retail", "experience_level": "strong"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "moderate", "provided_in_house": 0, "notes": "Partner network."},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": "Standard reporting only."},
            ],
        },
        {
            "vendor_name": "Lakeside Claims Administration",
            "headquarters_state": "IL",
            "company_size": "small_market",
            "years_in_business": 9,
            "website": "https://example.com/lakeside",
            "ideal_client_size": "50-500 employees",
            "program_type_fit": "guaranteed_cost",
            "pricing_level": "low",
            "satisfaction_score": 78,
            "avg_response_time_days": 3.8,
            "reporting_score": 5.5,
            "data_quality_score": 6.0,
            "source": "vendor_self_reported",
            "source_confidence": "low",
            "last_updated": "2024-06-15",
            "verified_by_human": 0,
            "notes": "Affordable option but limited verified performance data.",
            "states": [
                {"state_code": "IL", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "WI", "coverage_strength": "limited", "local_adjuster_network": 0},
                {"state_code": "IN", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "moderate", "primary_focus": 0},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 1},
            ],
            "industries": [
                {"industry": "retail", "experience_level": "moderate"},
                {"industry": "hospitality", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "limited", "provided_in_house": 0, "notes": "Handled through employer."},
                {"service_name": "dashboard_reporting", "service_level": "limited", "provided_in_house": 1, "notes": "PDF reports only."},
            ],
        },
        {
            "vendor_name": "Summit Risk Services",
            "headquarters_state": "CO",
            "company_size": "enterprise",
            "years_in_business": 31,
            "website": "https://example.com/summit-risk",
            "ideal_client_size": "1000+ employees",
            "program_type_fit": "self_insured, captive, high_deductible",
            "pricing_level": "high",
            "satisfaction_score": 89,
            "avg_response_time_days": 1.9,
            "reporting_score": 9.0,
            "data_quality_score": 8.5,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-01-09",
            "verified_by_human": 1,
            "notes": "Enterprise-focused TPA with strong analytics and national reach.",
            "states": [
                {"state_code": "MN", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "WI", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "IA", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "CA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "TX", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "FL", "coverage_strength": "strong", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "strong", "primary_focus": 0},
                {"claim_type": "auto_liability", "capability_level": "strong", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "moderate"},
                {"industry": "transportation", "experience_level": "strong"},
                {"industry": "healthcare", "experience_level": "strong"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "litigation_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": "Advanced dashboards."},
                {"service_name": "api_access", "service_level": "moderate", "provided_in_house": 1, "notes": "API available for enterprise clients."},
                {"service_name": "soc2_security", "service_level": "strong", "provided_in_house": 1, "notes": "SOC2 Type II available."},
            ],
        },
        {
            "vendor_name": "Coastal Claims Partners",
            "headquarters_state": "CA",
            "company_size": "mid_market",
            "years_in_business": 14,
            "website": "https://example.com/coastal-claims",
            "ideal_client_size": "250-2000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium_high",
            "satisfaction_score": 86,
            "avg_response_time_days": 2.0,
            "reporting_score": 8.0,
            "data_quality_score": 8.0,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-03-05",
            "verified_by_human": 1,
            "notes": "Strong western U.S. option, weaker Midwest coverage.",
            "states": [
                {"state_code": "CA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "OR", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "WA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "AZ", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "HI", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "NV", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "AK", "coverage_strength": "limited", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "healthcare", "experience_level": "strong"},
                {"industry": "technology", "experience_level": "moderate"},
                {"industry": "hospitality", "experience_level": "strong"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "spanish_language_support", "service_level": "strong", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Great Lakes Claims",
            "headquarters_state": "OH",
            "company_size": "mid_market",
            "years_in_business": 22,
            "website": "https://example.com/greatlakes",
            "ideal_client_size": "200-1800 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 87,
            "avg_response_time_days": 1.9,
            "reporting_score": 7.5,
            "data_quality_score": 6.5,
            "source": "multiple_sources",
            "source_confidence": "medium",
            "last_updated": "2025-12-10",
            "verified_by_human": 0,
            "notes": "CONFLICT: Source A reports states as OH, MI, PA, IN. Source B reports OH, MI, IN, KY only. RTW capability rated 'strong' in proposal but 'moderate' in broker notes.",
            "states": [
                {"state_code": "OH", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IN", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "PA", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "strong"},
                {"industry": "construction", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": "Conflicting data on capability level."},
                {"service_name": "nurse_case_management", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "medical_bill_review", "service_level": "strong", "provided_in_house": 0, "notes": "Partner service."},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Heartland TPA",
            "headquarters_state": "MO",
            "company_size": "small_market",
            "years_in_business": 16,
            "website": "https://example.com/heartland",
            "ideal_client_size": "100-800 employees",
            "program_type_fit": "high_deductible, guaranteed_cost",
            "pricing_level": "low",
            "satisfaction_score": 82,
            "avg_response_time_days": 2.5,
            "reporting_score": 6.5,
            "data_quality_score": 7.0,
            "source": "broker_profile",
            "source_confidence": "medium",
            "last_updated": "2026-01-22",
            "verified_by_human": 1,
            "notes": "Solid regional option for smaller employers. Limited technology.",
            "states": [
                {"state_code": "MO", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "KS", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "NE", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "limited", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "moderate", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "limited", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "moderate"},
                {"industry": "retail", "experience_level": "moderate"},
                {"industry": "hospitality", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "limited", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "limited", "provided_in_house": 0, "notes": "Partner network."},
                {"service_name": "dashboard_reporting", "service_level": "limited", "provided_in_house": 1, "notes": "Basic reporting only."},
            ],
        },
        {
            "vendor_name": "Atlantic Claims Group",
            "headquarters_state": "NY",
            "company_size": "mid_market",
            "years_in_business": 27,
            "website": "https://example.com/atlantic",
            "ideal_client_size": "500-3000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "high",
            "satisfaction_score": 88,
            "avg_response_time_days": 1.7,
            "reporting_score": 8.5,
            "data_quality_score": 8.5,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-02-18",
            "verified_by_human": 1,
            "notes": "Strong Northeast option, no Midwest presence.",
            "states": [
                {"state_code": "NY", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "NJ", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "PA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "CT", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "MA", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "DE", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "ME", "coverage_strength": "limited", "local_adjuster_network": 0},
                {"state_code": "NH", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "RI", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "VT", "coverage_strength": "limited", "local_adjuster_network": 0},
                {"state_code": "WV", "coverage_strength": "moderate", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "strong", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "manufacturing", "experience_level": "moderate"},
                {"industry": "healthcare", "experience_level": "strong"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "litigation_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "medical_bill_review", "service_level": "strong", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Southeast Risk Partners",
            "headquarters_state": "GA",
            "company_size": "mid_market",
            "years_in_business": 19,
            "website": "https://example.com/southeast-risk",
            "ideal_client_size": "300-2500 employees",
            "program_type_fit": "self_insured, high_deductible, guaranteed_cost",
            "pricing_level": "medium",
            "satisfaction_score": 85,
            "avg_response_time_days": 2.1,
            "reporting_score": 7.5,
            "data_quality_score": 7.5,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-01-30",
            "verified_by_human": 1,
            "notes": "Strong Southeast regional presence.",
            "states": [
                {"state_code": "GA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "FL", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "SC", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "NC", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "TN", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "AL", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MS", "coverage_strength": "moderate", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
                {"claim_type": "auto_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "hospitality", "experience_level": "strong"},
                {"industry": "retail", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "subrogation", "service_level": "moderate", "provided_in_house": 0, "notes": "Partner service."},
            ],
        },
        {
            "vendor_name": "Texas Claims Unlimited",
            "headquarters_state": "TX",
            "company_size": "mid_market",
            "years_in_business": 21,
            "website": "https://example.com/texas-claims",
            "ideal_client_size": "400-3000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 83,
            "avg_response_time_days": 2.3,
            "reporting_score": 7.0,
            "data_quality_score": 7.0,
            "source": "broker_profile",
            "source_confidence": "medium",
            "last_updated": "2025-10-05",
            "verified_by_human": 1,
            "notes": "Texas-focused TPA, limited experience outside state.",
            "states": [
                {"state_code": "TX", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "OK", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "LA", "coverage_strength": "limited", "local_adjuster_network": 0},
                {"state_code": "AR", "coverage_strength": "moderate", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
                {"claim_type": "auto_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "transportation", "experience_level": "strong"},
                {"industry": "manufacturing", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "litigation_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "spanish_language_support", "service_level": "strong", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Premier Property Claims",
            "headquarters_state": "FL",
            "company_size": "mid_market",
            "years_in_business": 15,
            "website": "https://example.com/premier-property",
            "ideal_client_size": "500-5000 employees",
            "program_type_fit": "self_insured",
            "pricing_level": "medium_high",
            "satisfaction_score": 86,
            "avg_response_time_days": 1.5,
            "reporting_score": 8.0,
            "data_quality_score": 8.0,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-02-25",
            "verified_by_human": 1,
            "notes": "Property and casualty specialist, limited WC experience.",
            "states": [
                {"state_code": "FL", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "TX", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "LA", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "SC", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "property", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
                {"claim_type": "workers_comp", "capability_level": "limited", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "real_estate", "experience_level": "strong"},
                {"industry": "hospitality", "experience_level": "strong"},
                {"industry": "retail", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "fraud_investigation", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "subrogation", "service_level": "strong", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Professional Liability TPA",
            "headquarters_state": "IL",
            "company_size": "small_market",
            "years_in_business": 12,
            "website": "https://example.com/pro-liability",
            "ideal_client_size": "200-1000 employees",
            "program_type_fit": "self_insured",
            "pricing_level": "high",
            "satisfaction_score": 87,
            "avg_response_time_days": 1.8,
            "reporting_score": 8.5,
            "data_quality_score": 8.0,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-01-15",
            "verified_by_human": 1,
            "notes": "Niche professional liability TPA, minimal WC capability.",
            "states": [
                {"state_code": "IL", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "OH", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "MO", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "professional_liability", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
                {"claim_type": "workers_comp", "capability_level": "limited", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "professional_services", "experience_level": "strong"},
                {"industry": "healthcare", "experience_level": "strong"},
                {"industry": "technology", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "litigation_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Legacy Claims Co.",
            "headquarters_state": "OH",
            "company_size": "mid_market",
            "years_in_business": 38,
            "website": "https://example.com/legacy",
            "ideal_client_size": "250-2000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 75,
            "avg_response_time_days": 4.2,
            "reporting_score": 5.0,
            "data_quality_score": 4.0,
            "source": "broker_database",
            "source_confidence": "medium",
            "last_updated": "2023-08-12",
            "verified_by_human": 0,
            "notes": "STALE DATA - Acquired by larger firm in 2024. Status unclear. Poor historical performance.",
            "states": [
                {"state_code": "OH", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "IN", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "KY", "coverage_strength": "limited", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "moderate", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "limited", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "limited", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "limited", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Midwest Claims Solutions",
            "headquarters_state": "WI",
            "company_size": "small_market",
            "years_in_business": 11,
            "website": "https://example.com/midwest-solutions",
            "ideal_client_size": "150-1000 employees",
            "program_type_fit": "high_deductible, guaranteed_cost",
            "pricing_level": "low",
            "satisfaction_score": 79,
            "avg_response_time_days": 3.1,
            "reporting_score": 6.0,
            "data_quality_score": 5.5,
            "source": "multiple_sources",
            "source_confidence": "low",
            "last_updated": "2025-09-20",
            "verified_by_human": 0,
            "notes": "CONFLICT: Source A lists satisfaction score 79, Source B lists 72. Proposal shows IA coverage but vendor website does not list IA. API access unclear.",
            "states": [
                {"state_code": "WI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MN", "coverage_strength": "limited", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "moderate", "primary_focus": 1},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "limited"},
                {"industry": "retail", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "limited", "provided_in_house": 0, "notes": "Conflicting information."},
                {"service_name": "dashboard_reporting", "service_level": "limited", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Regional Risk Administrators",
            "headquarters_state": "IA",
            "company_size": "small_market",
            "years_in_business": 7,
            "website": "https://example.com/regional-risk",
            "ideal_client_size": "50-500 employees",
            "program_type_fit": "guaranteed_cost",
            "pricing_level": "low",
            "satisfaction_score": 76,
            "avg_response_time_days": 3.5,
            "reporting_score": 5.5,
            "data_quality_score": 4.5,
            "source": "vendor_self_reported",
            "source_confidence": "low",
            "last_updated": "2023-11-05",
            "verified_by_human": 0,
            "notes": "Very stale data - over 2 years old. Unable to verify current capabilities.",
            "states": [
                {"state_code": "IA", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "NE", "coverage_strength": "limited", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "limited", "primary_focus": 1},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "limited"},
                {"industry": "retail", "experience_level": "limited"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "limited", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Horizon Claims Services",
            "headquarters_state": "MN",
            "company_size": "mid_market",
            "years_in_business": 20,
            "website": "https://example.com/horizon",
            "ideal_client_size": "300-2500 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 88,
            "avg_response_time_days": 1.8,
            "reporting_score": 8.0,
            "data_quality_score": 8.0,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-03-01",
            "verified_by_human": 1,
            "notes": "Strong Midwest WC TPA with good technology and reporting.",
            "states": [
                {"state_code": "MN", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "WI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "ND", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "SD", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "strong"},
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "transportation", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "medical_bill_review", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "utilization_review", "service_level": "moderate", "provided_in_house": 0, "notes": "Partner service."},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "api_access", "service_level": "moderate", "provided_in_house": 1, "notes": "Available for larger clients."},
            ],
        },
        {
            "vendor_name": "Pacific Northwest TPA",
            "headquarters_state": "WA",
            "company_size": "small_market",
            "years_in_business": 13,
            "website": "https://example.com/pnw-tpa",
            "ideal_client_size": "200-1200 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 84,
            "avg_response_time_days": 2.2,
            "reporting_score": 7.5,
            "data_quality_score": 7.5,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-02-10",
            "verified_by_human": 1,
            "notes": "Regional Northwest specialist.",
            "states": [
                {"state_code": "WA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "OR", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "ID", "coverage_strength": "moderate", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "limited", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "technology", "experience_level": "strong"},
                {"industry": "healthcare", "experience_level": "moderate"},
                {"industry": "construction", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Mountain States Claims",
            "headquarters_state": "CO",
            "company_size": "mid_market",
            "years_in_business": 17,
            "website": "https://example.com/mountain-states",
            "ideal_client_size": "250-2000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 85,
            "avg_response_time_days": 2.0,
            "reporting_score": 7.5,
            "data_quality_score": 7.5,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-01-18",
            "verified_by_human": 1,
            "notes": "Strong Mountain West and Plains presence.",
            "states": [
                {"state_code": "CO", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "WY", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MT", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "UT", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "NM", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "energy", "experience_level": "strong"},
                {"industry": "manufacturing", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Capital Risk Management",
            "headquarters_state": "VA",
            "company_size": "mid_market",
            "years_in_business": 23,
            "website": "https://example.com/capital-risk",
            "ideal_client_size": "400-3000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium_high",
            "satisfaction_score": 86,
            "avg_response_time_days": 1.9,
            "reporting_score": 8.0,
            "data_quality_score": 8.0,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-02-20",
            "verified_by_human": 1,
            "notes": "Mid-Atlantic specialist with strong public sector experience.",
            "states": [
                {"state_code": "VA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MD", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "DC", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "NC", "coverage_strength": "moderate", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "strong", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "public_entity", "experience_level": "strong"},
                {"industry": "education", "experience_level": "strong"},
                {"industry": "healthcare", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "litigation_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Occupational Health Claims",
            "headquarters_state": "TX",
            "company_size": "small_market",
            "years_in_business": 9,
            "website": "https://example.com/occ-health",
            "ideal_client_size": "100-800 employees",
            "program_type_fit": "high_deductible",
            "pricing_level": "medium_low",
            "satisfaction_score": 81,
            "avg_response_time_days": 2.4,
            "reporting_score": 6.5,
            "data_quality_score": 7.0,
            "source": "vendor_self_reported",
            "source_confidence": "medium",
            "last_updated": "2025-12-08",
            "verified_by_human": 0,
            "notes": "Niche occupational accident focus for alternative workforce.",
            "states": [
                {"state_code": "TX", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "AZ", "coverage_strength": "moderate", "local_adjuster_network": 0},
                {"state_code": "NM", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "occupational_accident", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "workers_comp", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "transportation", "experience_level": "strong"},
                {"industry": "construction", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "limited", "provided_in_house": 0, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "limited", "provided_in_house": 1, "notes": None},
            ],
        },
        {
            "vendor_name": "Platinum Claims Group",
            "headquarters_state": "IL",
            "company_size": "enterprise",
            "years_in_business": 35,
            "website": "https://example.com/platinum",
            "ideal_client_size": "2000+ employees",
            "program_type_fit": "self_insured, captive",
            "pricing_level": "high",
            "satisfaction_score": 90,
            "avg_response_time_days": 1.4,
            "reporting_score": 9.5,
            "data_quality_score": 9.0,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-03-10",
            "verified_by_human": 1,
            "notes": "Premium enterprise TPA with national reach and advanced analytics.",
            "states": [
                {"state_code": "IL", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MN", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "WI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "OH", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "CA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "TX", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "NY", "coverage_strength": "strong", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "strong", "primary_focus": 0},
                {"claim_type": "auto_liability", "capability_level": "strong", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "strong"},
                {"industry": "transportation", "experience_level": "strong"},
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "healthcare", "experience_level": "strong"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "medical_bill_review", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "utilization_review", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "pharmacy_benefit_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "litigation_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "subrogation", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "fraud_investigation", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": "Advanced analytics platform."},
                {"service_name": "api_access", "service_level": "strong", "provided_in_house": 1, "notes": "Full API suite."},
                {"service_name": "origami_integration", "service_level": "strong", "provided_in_house": 1, "notes": "Certified integration."},
                {"service_name": "soc2_security", "service_level": "strong", "provided_in_house": 1, "notes": "SOC2 Type II certified."},
            ],
        },
        {
            "vendor_name": "Evergreen Risk Services",
            "headquarters_state": "WI",
            "company_size": "mid_market",
            "years_in_business": 19,
            "website": "https://example.com/evergreen",
            "ideal_client_size": "300-2000 employees",
            "program_type_fit": "self_insured, high_deductible",
            "pricing_level": "medium",
            "satisfaction_score": 87,
            "avg_response_time_days": 1.9,
            "reporting_score": 7.5,
            "data_quality_score": 8.0,
            "source": "broker_profile",
            "source_confidence": "high",
            "last_updated": "2026-02-28",
            "verified_by_human": 1,
            "notes": "Strong Midwest option with particular strength in manufacturing and construction.",
            "states": [
                {"state_code": "WI", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "MN", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IL", "coverage_strength": "moderate", "local_adjuster_network": 1},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "strong"},
                {"industry": "construction", "experience_level": "strong"},
                {"industry": "transportation", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "strong", "provided_in_house": 1, "notes": "Dedicated RTW specialists."},
                {"service_name": "nurse_case_management", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "medical_bill_review", "service_level": "moderate", "provided_in_house": 0, "notes": "Partner service."},
                {"service_name": "dashboard_reporting", "service_level": "strong", "provided_in_house": 1, "notes": None},
                {"service_name": "origami_integration", "service_level": "moderate", "provided_in_house": 1, "notes": "Prior integration experience."},
            ],
        },
        {
            "vendor_name": "Apex Claims Management",
            "headquarters_state": "MN",
            "company_size": "small_market",
            "years_in_business": 8,
            "website": "https://example.com/apex",
            "ideal_client_size": "100-750 employees",
            "program_type_fit": "guaranteed_cost, high_deductible",
            "pricing_level": "low",
            "satisfaction_score": 80,
            "avg_response_time_days": 2.8,
            "reporting_score": 6.0,
            "data_quality_score": 6.5,
            "source": "proposal_summary",
            "source_confidence": "medium",
            "last_updated": "2025-11-30",
            "verified_by_human": 0,
            "notes": "Budget-friendly option but limited service capabilities and technology.",
            "states": [
                {"state_code": "MN", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "WI", "coverage_strength": "limited", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "moderate", "primary_focus": 1},
            ],
            "industries": [
                {"industry": "retail", "experience_level": "moderate"},
                {"industry": "hospitality", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "limited", "provided_in_house": 0, "notes": "Minimal support."},
                {"service_name": "dashboard_reporting", "service_level": "limited", "provided_in_house": 1, "notes": "Basic Excel reports."},
            ],
        },
        {
            "vendor_name": "United Claims Services",
            "headquarters_state": "MO",
            "company_size": "mid_market",
            "years_in_business": 26,
            "website": "https://example.com/united",
            "ideal_client_size": "250-2500 employees",
            "program_type_fit": "self_insured, high_deductible, guaranteed_cost",
            "pricing_level": "medium",
            "satisfaction_score": 83,
            "avg_response_time_days": 2.2,
            "reporting_score": 7.0,
            "data_quality_score": 7.5,
            "source": "broker_database",
            "source_confidence": "high",
            "last_updated": "2026-01-25",
            "verified_by_human": 1,
            "notes": "Reliable regional TPA with broad Midwest and Central Plains coverage.",
            "states": [
                {"state_code": "MO", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "KS", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "NE", "coverage_strength": "strong", "local_adjuster_network": 1},
                {"state_code": "IA", "coverage_strength": "moderate", "local_adjuster_network": 1},
                {"state_code": "OK", "coverage_strength": "moderate", "local_adjuster_network": 0},
            ],
            "claim_types": [
                {"claim_type": "workers_comp", "capability_level": "strong", "primary_focus": 1},
                {"claim_type": "general_liability", "capability_level": "moderate", "primary_focus": 0},
            ],
            "industries": [
                {"industry": "manufacturing", "experience_level": "moderate"},
                {"industry": "transportation", "experience_level": "moderate"},
                {"industry": "retail", "experience_level": "moderate"},
            ],
            "services": [
                {"service_name": "return_to_work", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "nurse_case_management", "service_level": "moderate", "provided_in_house": 1, "notes": None},
                {"service_name": "dashboard_reporting", "service_level": "moderate", "provided_in_house": 1, "notes": None},
            ],
        },
    ]

    for vendor in vendors:
        vendor_id = insert_vendor(cursor, vendor)

        insert_many_to_vendor_table(cursor, "vendor_states", vendor_id, vendor["states"])
        insert_many_to_vendor_table(cursor, "vendor_claim_types", vendor_id, vendor["claim_types"])
        insert_many_to_vendor_table(cursor, "vendor_industries", vendor_id, vendor["industries"])
        insert_many_to_vendor_table(cursor, "vendor_services", vendor_id, vendor["services"])


def seed_buyer_requests(cursor):
    buyer_requests = [
        {
            "buyer_name": "ABC Manufacturing",
            "industry": "manufacturing",
            "sub_industry": "metal fabrication",
            "employee_count": 850,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 220,
            "implementation_timeline_days": 90,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 4,
            "priority_services": 5,
            "priority_reporting": 4,
            "priority_technology": 3,
            "priority_cost": 3,
            "narrative_request": "Need a WC TPA for a self-insured manufacturing client in MN, WI, and IA. Return-to-work and reporting are major issues.",
            "pain_points": "Slow response, poor RTW coordination, weak reporting.",
            "excluded_vendors": None,
            "states": ["MN", "WI", "IA"],
            "services": [
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 1, "priority_level": "required"},
                {"service_name": "nurse_case_management", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Pacific Healthcare Group",
            "industry": "healthcare",
            "sub_industry": "senior living",
            "employee_count": 1300,
            "program_type": "high_deductible",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 340,
            "implementation_timeline_days": 120,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 4,
            "priority_reporting": 4,
            "priority_technology": 3,
            "priority_cost": 2,
            "narrative_request": "Healthcare client in CA, OR, and WA needs workers compensation support with nurse case management and Spanish language support.",
            "pain_points": "High injury frequency, language access concerns, inconsistent claim reviews.",
            "excluded_vendors": None,
            "states": ["CA", "OR", "WA"],
            "services": [
                {"service_name": "nurse_case_management", "required": 1, "priority_level": "required"},
                {"service_name": "spanish_language_support", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "National Logistics Co.",
            "industry": "transportation",
            "sub_industry": "freight and delivery",
            "employee_count": 4200,
            "program_type": "captive",
            "claim_type_needed": "auto_liability",
            "annual_claim_volume": 650,
            "implementation_timeline_days": 180,
            "priority_geography": 4,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 4,
            "priority_reporting": 5,
            "priority_technology": 5,
            "priority_cost": 2,
            "narrative_request": "Large transportation client needs auto liability and GL support with strong analytics, litigation management, API access, and SOC2.",
            "pain_points": "High litigation rate, poor data exports, inconsistent reserve reviews.",
            "excluded_vendors": None,
            "states": ["TX", "CA", "FL"],
            "services": [
                {"service_name": "litigation_management", "required": 1, "priority_level": "required"},
                {"service_name": "api_access", "required": 1, "priority_level": "required"},
                {"service_name": "soc2_security", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Northeast Construction Group",
            "industry": "construction",
            "sub_industry": "commercial construction",
            "employee_count": 650,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 180,
            "implementation_timeline_days": 90,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 4,
            "priority_reporting": 3,
            "priority_technology": 2,
            "priority_cost": 3,
            "narrative_request": "Construction client in NY, NJ, and PA needs WC TPA with strong litigation management and construction experience.",
            "pain_points": "High litigation rate, poor case reserve management, need construction-specific expertise.",
            "excluded_vendors": None,
            "states": ["NY", "NJ", "PA"],
            "services": [
                {"service_name": "litigation_management", "required": 1, "priority_level": "required"},
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "medical_bill_review", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Mountain Tech Industries",
            "industry": "manufacturing",
            "sub_industry": "electronics",
            "employee_count": 420,
            "program_type": "high_deductible",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 85,
            "implementation_timeline_days": 120,
            "priority_geography": 4,
            "priority_claims": 4,
            "priority_industry": 3,
            "priority_services": 4,
            "priority_reporting": 5,
            "priority_technology": 5,
            "priority_cost": 2,
            "narrative_request": "Colorado-based manufacturing client needs WC TPA with strong technology and data export capabilities.",
            "pain_points": "Current TPA lacks API access and modern reporting. Need RMIS integration.",
            "excluded_vendors": None,
            "states": ["CO", "UT", "WY"],
            "services": [
                {"service_name": "api_access", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 1, "priority_level": "required"},
                {"service_name": "origami_integration", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Midwest Retail Chain",
            "industry": "retail",
            "sub_industry": "grocery",
            "employee_count": 1850,
            "program_type": "guaranteed_cost",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 320,
            "implementation_timeline_days": 60,
            "priority_geography": 5,
            "priority_claims": 4,
            "priority_industry": 3,
            "priority_services": 3,
            "priority_reporting": 3,
            "priority_technology": 2,
            "priority_cost": 5,
            "narrative_request": "Budget-conscious retail client in MN and WI needs affordable WC coverage with basic services.",
            "pain_points": "Cost is primary concern. Current program too expensive. Need reliable basic service.",
            "excluded_vendors": "Summit Risk Services, Platinum Claims Group",
            "states": ["MN", "WI"],
            "services": [
                {"service_name": "return_to_work", "required": 0, "priority_level": "preferred"},
                {"service_name": "dashboard_reporting", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Southeast Hospitality Partners",
            "industry": "hospitality",
            "sub_industry": "hotels",
            "employee_count": 980,
            "program_type": "high_deductible",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 210,
            "implementation_timeline_days": 90,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 4,
            "priority_reporting": 4,
            "priority_technology": 3,
            "priority_cost": 3,
            "narrative_request": "Hospitality client in GA, FL, and SC needs WC TPA with strong nurse case management and hospitality experience.",
            "pain_points": "High frequency of back injuries and slip-and-falls. Need proactive medical management.",
            "excluded_vendors": None,
            "states": ["GA", "FL", "SC"],
            "services": [
                {"service_name": "nurse_case_management", "required": 1, "priority_level": "required"},
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "medical_bill_review", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Public School District 402",
            "industry": "education",
            "sub_industry": "K-12 education",
            "employee_count": 1200,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 145,
            "implementation_timeline_days": 150,
            "priority_geography": 5,
            "priority_claims": 4,
            "priority_industry": 5,
            "priority_services": 4,
            "priority_reporting": 5,
            "priority_technology": 3,
            "priority_cost": 4,
            "narrative_request": "Public school district in VA needs WC TPA with public sector experience and strong reporting for board oversight.",
            "pain_points": "Need transparent reporting for school board. Must understand public entity requirements.",
            "excluded_vendors": None,
            "states": ["VA", "MD"],
            "services": [
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 1, "priority_level": "required"},
                {"service_name": "nurse_case_management", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Great Lakes Manufacturing",
            "industry": "manufacturing",
            "sub_industry": "automotive parts",
            "employee_count": 720,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 195,
            "implementation_timeline_days": 90,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 5,
            "priority_reporting": 4,
            "priority_technology": 3,
            "priority_cost": 3,
            "narrative_request": "Manufacturing client in OH, MI, and IN needs WC TPA with strong RTW and manufacturing expertise. Switching from Legacy Claims Co due to poor service.",
            "pain_points": "Current TPA (Legacy Claims Co) has slow response times and poor RTW outcomes. Need immediate improvement.",
            "excluded_vendors": "Legacy Claims Co.",
            "states": ["OH", "MI", "IN"],
            "services": [
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "nurse_case_management", "required": 1, "priority_level": "required"},
                {"service_name": "medical_bill_review", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Small Town Employers Group",
            "industry": "manufacturing",
            "sub_industry": "food processing",
            "employee_count": 180,
            "program_type": "guaranteed_cost",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 45,
            "implementation_timeline_days": 60,
            "priority_geography": 4,
            "priority_claims": 4,
            "priority_industry": 3,
            "priority_services": 3,
            "priority_reporting": 2,
            "priority_technology": 1,
            "priority_cost": 5,
            "narrative_request": "Small employer in Iowa needs affordable WC TPA with basic service. Budget is tight.",
            "pain_points": "Very cost-sensitive. Need basic reliable service without premium features.",
            "excluded_vendors": None,
            "states": ["IA"],
            "services": [
                {"service_name": "return_to_work", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Premium Hotel Corporation",
            "industry": "hospitality",
            "sub_industry": "luxury hotels",
            "employee_count": 3200,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 580,
            "implementation_timeline_days": 180,
            "priority_geography": 4,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 5,
            "priority_reporting": 5,
            "priority_technology": 5,
            "priority_cost": 1,
            "narrative_request": "National luxury hotel chain needs premium WC TPA with full service suite, advanced analytics, API integration, and SOC2 compliance.",
            "pain_points": "Need enterprise-grade service. Cost less important than quality and technology capabilities.",
            "excluded_vendors": None,
            "states": ["CA", "NY", "FL", "IL", "TX"],
            "services": [
                {"service_name": "nurse_case_management", "required": 1, "priority_level": "required"},
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "medical_bill_review", "required": 1, "priority_level": "required"},
                {"service_name": "utilization_review", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 1, "priority_level": "required"},
                {"service_name": "api_access", "required": 1, "priority_level": "required"},
                {"service_name": "soc2_security", "required": 1, "priority_level": "required"},
                {"service_name": "fraud_investigation", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Texas Energy Services",
            "industry": "energy",
            "sub_industry": "oil and gas services",
            "employee_count": 890,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 175,
            "implementation_timeline_days": 120,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 4,
            "priority_reporting": 4,
            "priority_technology": 3,
            "priority_cost": 3,
            "narrative_request": "Energy sector client in Texas and surrounding states needs WC TPA with high-severity claim experience and strong litigation management.",
            "pain_points": "Complex claims including catastrophic injuries. Need experienced litigation support.",
            "excluded_vendors": None,
            "states": ["TX", "OK", "LA"],
            "services": [
                {"service_name": "litigation_management", "required": 1, "priority_level": "required"},
                {"service_name": "nurse_case_management", "required": 1, "priority_level": "required"},
                {"service_name": "return_to_work", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Multi-State Distribution Company",
            "industry": "transportation",
            "sub_industry": "warehousing",
            "employee_count": 2400,
            "program_type": "high_deductible",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 410,
            "implementation_timeline_days": 120,
            "priority_geography": 5,
            "priority_claims": 5,
            "priority_industry": 4,
            "priority_services": 4,
            "priority_reporting": 5,
            "priority_technology": 4,
            "priority_cost": 3,
            "narrative_request": "Distribution company with facilities across Midwest needs WC TPA with multi-state coordination and strong reporting.",
            "pain_points": "Current TPA struggles with multi-location consistency. Need unified reporting across all states.",
            "excluded_vendors": None,
            "states": ["IL", "IN", "OH", "WI", "MN"],
            "services": [
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "nurse_case_management", "required": 1, "priority_level": "required"},
                {"service_name": "dashboard_reporting", "required": 1, "priority_level": "required"},
                {"service_name": "medical_bill_review", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Rare State Combo Inc",
            "industry": "manufacturing",
            "sub_industry": "plastics",
            "employee_count": 540,
            "program_type": "self_insured",
            "claim_type_needed": "workers_comp",
            "annual_claim_volume": 125,
            "implementation_timeline_days": 90,
            "priority_geography": 5,
            "priority_claims": 4,
            "priority_industry": 3,
            "priority_services": 4,
            "priority_reporting": 3,
            "priority_technology": 2,
            "priority_cost": 3,
            "narrative_request": "Manufacturing client needs WC TPA for unusual state combination: MT, WY, and ID. Local presence important.",
            "pain_points": "Hard to find TPAs with strong presence in these states. Need local adjusters.",
            "excluded_vendors": None,
            "states": ["MT", "WY", "ID"],
            "services": [
                {"service_name": "return_to_work", "required": 1, "priority_level": "required"},
                {"service_name": "nurse_case_management", "required": 0, "priority_level": "preferred"},
            ],
        },
        {
            "buyer_name": "Property Management Holdings",
            "industry": "real_estate",
            "sub_industry": "commercial property management",
            "employee_count": 620,
            "program_type": "self_insured",
            "claim_type_needed": "general_liability",
            "annual_claim_volume": 95,
            "implementation_timeline_days": 120,
            "priority_geography": 4,
            "priority_claims": 5,
            "priority_industry": 5,
            "priority_services": 3,
            "priority_reporting": 4,
            "priority_technology": 3,
            "priority_cost": 3,
            "narrative_request": "Property management company in FL and TX needs GL TPA with property sector experience and subrogation expertise.",
            "pain_points": "Slip-and-fall claims and property damage. Need strong subrogation to recover costs.",
            "excluded_vendors": None,
            "states": ["FL", "TX"],
            "services": [
                {"service_name": "subrogation", "required": 1, "priority_level": "required"},
                {"service_name": "fraud_investigation", "required": 0, "priority_level": "preferred"},
                {"service_name": "dashboard_reporting", "required": 0, "priority_level": "preferred"},
            ],
        },
    ]

    for buyer in buyer_requests:
        cursor.execute(
            """
            INSERT INTO buyer_requests (
                buyer_name,
                industry,
                sub_industry,
                employee_count,
                program_type,
                claim_type_needed,
                annual_claim_volume,
                implementation_timeline_days,
                priority_geography,
                priority_claims,
                priority_industry,
                priority_services,
                priority_reporting,
                priority_technology,
                priority_cost,
                narrative_request,
                pain_points,
                excluded_vendors
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                buyer["buyer_name"],
                buyer["industry"],
                buyer["sub_industry"],
                buyer["employee_count"],
                buyer["program_type"],
                buyer["claim_type_needed"],
                buyer["annual_claim_volume"],
                buyer["implementation_timeline_days"],
                buyer["priority_geography"],
                buyer["priority_claims"],
                buyer["priority_industry"],
                buyer["priority_services"],
                buyer["priority_reporting"],
                buyer["priority_technology"],
                buyer["priority_cost"],
                buyer["narrative_request"],
                buyer["pain_points"],
                buyer["excluded_vendors"],
            ),
        )

        buyer_request_id = cursor.lastrowid

        for state_code in buyer["states"]:
            cursor.execute(
                """
                INSERT INTO buyer_required_states (
                    buyer_request_id,
                    state_code,
                    required
                )
                VALUES (?, ?, ?)
                """,
                (buyer_request_id, state_code, 1),
            )

        for service in buyer["services"]:
            cursor.execute(
                """
                INSERT INTO buyer_required_services (
                    buyer_request_id,
                    service_name,
                    required,
                    priority_level
                )
                VALUES (?, ?, ?, ?)
                """,
                (
                    buyer_request_id,
                    service["service_name"],
                    service["required"],
                    service["priority_level"],
                ),
            )


def clear_existing_data(cursor):
    cursor.executescript(
        """
        DELETE FROM validation_results;
        DELETE FROM match_results;
        DELETE FROM buyer_required_services;
        DELETE FROM buyer_required_states;
        DELETE FROM buyer_requests;
        DELETE FROM vendor_services;
        DELETE FROM vendor_industries;
        DELETE FROM vendor_claim_types;
        DELETE FROM vendor_states;
        DELETE FROM vendors;
        """
    )


def print_summary(cursor):
    tables = [
        "vendors",
        "vendor_states",
        "vendor_claim_types",
        "vendor_industries",
        "vendor_services",
        "buyer_requests",
        "buyer_required_states",
        "buyer_required_services",
    ]

    print("Seed data loaded successfully:")
    for table in tables:
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        count = cursor.fetchone()[0]
        print(f"- {table}: {count} records")


def main():
    conn = connect_db()
    cursor = conn.cursor()

    clear_existing_data(cursor)
    seed_vendors(cursor)
    seed_buyer_requests(cursor)

    conn.commit()
    print_summary(cursor)
    conn.close()


if __name__ == "__main__":
    main()